# Generated by Django 4.2.30 on 2026-09-02 16:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=100)),
                ('species', models.CharField(max_length=100)),
                ('location', models.CharField(blank=True, help_text='Optional: Where the plant is located, e.g Kitchen windowsill.', max_length=100)),
                ('acquired_date', models.DateField(blank=True, help_text='Date plant acquired.', null=True)),
                ('water_frequency_days', models.PositiveIntegerField(default=7, help_text='How often to water the plant, in days.')),
                ('light_needs', models.CharField(choices=[('low', 'Low light'), ('medium', 'Medium light'), ('bright', 'Bright indirect light'), ('direct', 'Direct sunlight')], default='medium', help_text='Plant light requirements.', max_length=25)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the plant.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plants', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['nickname'],
            },
        ),
        migrations.CreateModel(
            name='CareLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('action', models.CharField(choices=[('water', 'Watered'), ('fertilize', 'Fertilized'), ('prune', 'Pruned'), ('repot', 'Repotted'), ('check', 'Health check'), ('other', 'Other')], max_length=25)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='care_logs', to='plants.plant')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
